### ISSUE TITLE
tests now fail

### ISSUE THREAD

**Issue by icefox** [Shopify/shopify-fulfillment-integration#3]
When running 'bundle exec rake test' it looks like the testing framework that was being used has been deprecated and it fails to run any tests and just outputs warnings about how the tests should be upgraded :\

$ bundle exec rake test
/usr/bin/ruby2.1 -I"lib:test" -I"/var/lib/gems/2.1.0/gems/rake-10.1.1/lib" "/var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb" "test/*_test.rb" 
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /usr/lib/ruby/2.1.0/test/unit.rb:1:in `require'
  /usr/lib/ruby/2.1.0/test/unit.rb:1:in `<top (required)>'
  /home/ben/public_html/shopify-fulfillment-integration/test/test_helper.rb:4:in `require'
  /home/ben/public_html/shopify-fulfillment-integration/test/test_helper.rb:4:in `<top (required)>'
  /home/ben/public_html/shopify-fulfillment-integration/test/app_test.rb:1:in `require'
  /home/ben/public_html/shopify-fulfillment-integration/test/app_test.rb:1:in `<top (required)>'
  /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:10:in `require'
  /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
  /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:9:in `each'
  /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:9:in `block in <main>'
  /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:4:in `select'
  /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:4:in `<main>'
MiniTest::Unit::TestCase is now Minitest::Test. From /usr/lib/ruby/2.1.0/test/unit/testcase.rb:8:in `<module:Unit>'
/usr/lib/ruby/2.1.0/test/unit.rb:676:in `<class:Runner>': undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)
	from /usr/lib/ruby/2.1.0/test/unit.rb:261:in `<module:Unit>'
	from /usr/lib/ruby/2.1.0/test/unit.rb:15:in `<module:Test>'
	from /usr/lib/ruby/2.1.0/test/unit.rb:7:in `<top (required)>'
	from /home/ben/public_html/shopify-fulfillment-integration/test/test_helper.rb:4:in `require'
	from /home/ben/public_html/shopify-fulfillment-integration/test/test_helper.rb:4:in `<top (required)>'
	from /home/ben/public_html/shopify-fulfillment-integration/test/app_test.rb:1:in `require'
	from /home/ben/public_html/shopify-fulfillment-integration/test/app_test.rb:1:in `<top (required)>'
	from /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:10:in `require'
	from /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
	from /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:9:in `each'
	from /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:9:in `block in <main>'
	from /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:4:in `select'
	from /var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -I"lib:test" -I"/var/lib/gems/2.1.0/gems/rake-10.1.1/lib" "/var/lib/gems/2.1.0/gems/rake-10.1.1/lib/rake/rake_test_loader.rb" "test/*_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)

**Comment by icefox** [comment]
This is some sort of dependency issue depending on what gems/ruby are on the OS.  Works on one box but not the other.
